name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:
    inputs:
      url: 
        description: 'Url'
        required: true
        default: 'www.google.com'
      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - id: current_branch
      shell: bash
      run: |
        echo $GITHUB_EVENT_NAME
        if {{ $GITHUB_EVENT_NAME == 'pull_request' }}
          then
          echo "::set-output name=branch:${GITHUB_HEAD_REF##*/}"
        else
          echo "::set-output name=branch:${GITHUB_REF##*/}"
        fi
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=sha_long::$(git rev-parse HEAD)"
          
    - name: Checkout ${{ steps.current_branch.outputs.branch }} branch
      uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
